import { randomUUID } from "node:crypto";
import type { ModelReference } from "./contracts/common.js";
import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import { HttpProtocolError, type NormalizedChatRequest, type NormalizedChatResult, type NormalizedChatStreamEvent } from "./http-protocol.js";
import { parseOllamaChat, parseOllamaGenerate, parseOpenAIChat, serializeOllamaChat, serializeOllamaGenerate, serializeOllamaStream, serializeOpenAIChat, serializeOpenAIStream } from "./http-adapters.js";
import type { ContinuationStreamEvent, ExternalToolContinuationManager } from "./http-continuation.js";
import type { HttpRunRegistry } from "./http-runs.js";
import type { AvailableModel } from "./contracts/common.js";

export type HttpListenerOptions = { bearerToken?: string; maxBodyBytes?: number };
export type HttpExecutionServices = { complete(request: NormalizedChatRequest, signal?: AbortSignal): Promise<NormalizedChatResult>; stream(request: NormalizedChatRequest, signal?: AbortSignal): AsyncIterable<NormalizedChatStreamEvent>; continuation?: Pick<ExternalToolContinuationManager, "start" | "resumeBatch" | "matchPending">; listModels?: () => AvailableModel[]; };
function json(data: unknown, status = 200, headers?: HeadersInit): Response { return new Response(JSON.stringify(data), { status, headers: { "content-type": "application/json", ...headers } }); }
function errorResponse(error: unknown): Response { if (error instanceof HttpProtocolError) return json({ error: { message: error.message, type: error.code } }, error.code === "http_invalid_request" ? 400 : 422); return json({ error: { message: error instanceof Error ? error.message : String(error), type: "server_error" } }, 500); }
async function readLimitedBody(request: Request, maximum: number): Promise<string> { const declared = request.headers.get("content-length"); if (declared && Number(declared) > maximum) throw new HttpProtocolError("Request body is too large", "http_invalid_request"); if (!request.body) return ""; const reader = request.body.getReader(); const chunks: Uint8Array[] = []; let size = 0; try { while (true) { const next = await reader.read(); if (next.done) break; size += next.value.byteLength; if (size > maximum) { await reader.cancel(); throw new HttpProtocolError("Request body is too large", "http_invalid_request"); } chunks.push(next.value); } } finally { reader.releaseLock(); } const total = new Uint8Array(size); let offset = 0; for (const chunk of chunks) { total.set(chunk, offset); offset += chunk.byteLength; } return new TextDecoder().decode(total); }
function streamResponse<T>(events: AsyncIterable<T>, encode: (event: T) => string, contentType: string, signal?: AbortSignal, cleanup?: (event?: T) => void, terminal?: (error: unknown) => T | undefined): Response { const encoder = new TextEncoder(); let iterator: AsyncIterator<T> | undefined; let lastWrite = Date.now(); let keepaliveTimer: ReturnType<typeof setInterval> | undefined; const stopKeepalive = () => { if (keepaliveTimer) { clearInterval(keepaliveTimer); keepaliveTimer = undefined; } };
        const body = new ReadableStream<Uint8Array>({ async start(controller) { iterator = events[Symbol.asyncIterator]();
          // SSE clients (pi's undici fetch has a 5-minute idle timeout) need
          // bytes during long silent phases like multi-step planning.
          if (contentType === "text/event-stream") keepaliveTimer = setInterval(() => { if (Date.now() - lastWrite < 15_000) return; try { controller.enqueue(encoder.encode(": keep-alive\n\n")); lastWrite = Date.now(); } catch { stopKeepalive(); } }, 5_000);
          try { while (true) { if (signal?.aborted) { stopKeepalive(); await iterator.return?.(); controller.error(new DOMException("Aborted", "AbortError")); return; } const next = await iterator.next(); if (next.done) { stopKeepalive(); cleanup?.(); controller.close(); return; } cleanup?.(next.value); controller.enqueue(encoder.encode(encode(next.value))); lastWrite = Date.now(); } } catch (error) {
          // Give clients a proper terminal frame so they see finish_reason
          // instead of a bare "stream ended" failure.
          stopKeepalive();
          const last = terminal?.(error);
          if (last !== undefined) { try { controller.enqueue(encoder.encode(encode(last))); controller.close(); return; } catch { /* fall through to surfacing the original error */ } }
          controller.error(error);
        } }, async cancel() { stopKeepalive(); await iterator?.return?.(); cleanup?.(); } }); return new Response(body, { status: 200, headers: { "content-type": contentType, "cache-control": "no-cache", connection: "keep-alive" } }); }
function safeToolArguments(args: unknown): string { if (typeof args === "string") { try { JSON.parse(args); return args; } catch { return "{}"; } } try { return JSON.stringify(args ?? {}); } catch { return "{}"; } }
function serializeContinuation(event: ContinuationStreamEvent, protocol: "openai" | "ollama", generate = false): Record<string, unknown> {
  // OpenAI clients get standard tool_calls deltas (tool-call id = continuation
  // id) so any compliant intermediary can execute tools and send results back
  // as tool messages; the follow-up request is matched to the paused run.
  const serializePause = (requestId: string, model: ModelReference, calls: Array<{ continuationId: string; name: string; arguments: unknown }>) => {
    if (protocol === "openai") return { id: `chatcmpl-${requestId}`, object: "chat.completion.chunk", model: `${model.provider}/${model.id}`, choices: [{ index: 0, delta: { tool_calls: calls.map((call, index) => ({ index, id: call.continuationId, type: "function", function: { name: call.name, arguments: safeToolArguments(call.arguments) } })) }, finish_reason: "tool_calls" }] };
    return { minai_continuation: true, request_id: requestId, calls };
  };
  if (event.type === "tool_pause_batch") return serializePause(event.requestId, event.model, event.calls);
  if (event.type === "tool_pause") return serializePause(event.requestId, event.model, [event]);
  const chat = event as NormalizedChatStreamEvent;
  return protocol === "openai" ? serializeOpenAIStream(chat) : serializeOllamaStream(chat, generate);
}

export type MinaiHttpServer = { server: Server; address: () => string | object | null; close: () => Promise<void> };

export class MinaiHttpHandler {
  constructor(private readonly services: HttpExecutionServices, private readonly options: HttpListenerOptions = {}, private readonly runs?: HttpRunRegistry) {}
  async handle(request: Request): Promise<Response> {
    try {
      if (this.options.bearerToken && request.headers.get("authorization") !== `Bearer ${this.options.bearerToken}`) return json({ error: { message: "Unauthorized", type: "authentication_error" } }, 401, { "www-authenticate": "Bearer" });
      const url = new URL(request.url);
      if (request.method === "GET" && url.pathname === "/health") return json({ status: "ok" });
      if (request.method === "GET" && url.pathname === "/v1/models") return this.modelsResponse("openai");
      if (request.method === "GET" && url.pathname === "/api/tags") return this.modelsResponse("ollama");
      if (request.method === "GET" && url.pathname === "/metrics") return json({ http_runs: this.runs?.metrics() ?? { active: 0, registered: 0, cancelled: 0, stopping: false } });
      if (request.method === "POST" && url.pathname.startsWith("/v1/runs/") && url.pathname.endsWith("/cancel")) return this.cancelResponse(request, url.pathname.slice("/v1/runs/".length, -"/cancel".length));
      if (request.method !== "POST") return json({ error: { message: "Method not allowed", type: "method_not_allowed" } }, 405, { allow: "GET, POST" });
      if (url.pathname.startsWith("/v1/continuations/")) return this.handleContinuation(request, url.pathname.slice("/v1/continuations/".length));
      const bodyText = await readLimitedBody(request, this.options.maxBodyBytes ?? 4_000_000); let body: unknown; try { body = JSON.parse(bodyText); } catch { throw new HttpProtocolError("Request body must be valid JSON", "http_invalid_request"); }
      const requestId = request.headers.get("x-request-id") ?? randomUUID(); let normalized: NormalizedChatRequest; let kind: "openai" | "ollama-chat" | "ollama-generate";
      if (url.pathname === "/v1/chat/completions") { normalized = parseOpenAIChat(body as Parameters<typeof parseOpenAIChat>[0], requestId); kind = "openai"; } else if (url.pathname === "/api/chat") { normalized = parseOllamaChat(body as Parameters<typeof parseOllamaChat>[0], requestId); kind = "ollama-chat"; } else if (url.pathname === "/api/generate") { normalized = parseOllamaGenerate(body as Parameters<typeof parseOllamaGenerate>[0], requestId); kind = "ollama-generate"; } else return json({ error: { message: "Not found", type: "not_found" } }, 404);
      // A follow-up request carrying tool results resumes the paused run
      // (standard OpenAI flow: tool_call ids are continuation ids).
      const resumedResults = kind === "openai" ? this.toolResultContinuations(normalized) : undefined;
      if (resumedResults && this.services.continuation) {
        const owner = request.headers.get("x-minai-owner") ?? undefined;
        const continuationIds = Object.keys(resumedResults);
        if (this.runs) for (const continuationId of continuationIds) if (!this.runs.ownsContinuation(continuationId, owner)) throw new HttpProtocolError("Continuation is not owned by caller", "http_invalid_request");
        const events = this.services.continuation.resumeBatch(resumedResults, request.signal);
        if (this.runs) for (const continuationId of continuationIds) this.runs.consumeContinuation(continuationId, owner);
        return streamResponse(events, (event) => `data: ${JSON.stringify(serializeContinuation(event, "openai"))}\n\n`, "text/event-stream", request.signal);
      }
      if (normalized.tools?.length) { if (!this.services.continuation) return json({ error: { message: "Tool continuation is unavailable", type: "not_implemented" } }, 501); if (!normalized.stream) return json({ error: { message: "Tool calls require stream mode in this slice", type: "unsupported" } }, 422); const owner = request.headers.get("x-minai-owner") ?? undefined; const run = this.runs?.register({ id: requestId, owner }); this.runs?.update(requestId, { model: `${normalized.model.provider}/${normalized.model.id}`, thinking: JSON.stringify(normalized.thinking ?? "off"), currentTask: "tool-continuation" }); const signal = run?.controller.signal ?? request.signal; const events = this.services.continuation.start(normalized, signal); const protocol = kind === "openai" ? "openai" : "ollama"; return streamResponse(events, (event) => { if (event.type === "tool_pause_batch") for (const call of event.calls) this.runs?.bindContinuation(call.continuationId, requestId, owner); else if (event.type === "tool_pause") this.runs?.bindContinuation(event.continuationId, requestId, owner); return protocol === "openai" ? `data: ${JSON.stringify(serializeContinuation(event, protocol, kind === "ollama-generate"))}\n\n` : `${JSON.stringify(serializeContinuation(event, protocol, kind === "ollama-generate"))}\n`; }, kind === "openai" ? "text/event-stream" : "application/x-ndjson", signal, (event) => { this.observeRun(requestId, event); if (!event) { this.runs?.remove(requestId); return; } if (event?.type === "tool_pause_batch") this.runs?.update(requestId, { continuation: event.calls.map((call) => call.continuationId).join(","), currentTask: "waiting-for-tools" }); else if (event?.type === "tool_pause") this.runs?.update(requestId, { continuation: event.continuationId, currentTask: "waiting-for-tool" }); if (event?.type === "tool_pause_batch" || event?.type === "tool_pause") return; if (event?.type === "done") this.runs?.remove(requestId); }); }
      if (normalized.stream) { const run = this.runs?.register({ id: requestId }); this.runs?.update(requestId, { model: `${normalized.model.provider}/${normalized.model.id}`, guidance: request.headers.get("x-minai-guidance") ?? undefined, thinking: JSON.stringify(normalized.thinking ?? "off"), currentTask: "guidance/model selection", phase: "guidance", progress: "request accepted; resolving guidance" }); const signal = run?.controller.signal ?? request.signal; const events = this.services.stream(normalized, signal); if (kind === "openai") return streamResponse(events, (event) => `data: ${JSON.stringify(serializeOpenAIStream(event))}\n\n`, "text/event-stream", signal, (event) => { this.observeRun(requestId, event); if (!event || event?.type === "done") this.runs?.remove(requestId); }, (error): NormalizedChatStreamEvent => ({ type: "done", result: { requestId, model: normalized.model, text: `MINAI stream failed: ${error instanceof Error ? error.message : String(error)}`, finishReason: "error" } })); return streamResponse(events, (event) => `${JSON.stringify(serializeOllamaStream(event, kind === "ollama-generate"))}\n`, "application/x-ndjson", signal, (event) => { this.observeRun(requestId, event); if (event?.type === "done") this.runs?.remove(requestId); }, (error): NormalizedChatStreamEvent => ({ type: "done", result: { requestId, model: normalized.model, text: `MINAI stream failed: ${error instanceof Error ? error.message : String(error)}`, finishReason: "error" } })); }
      const run = this.runs?.register({ id: requestId }); this.runs?.update(requestId, { model: `${normalized.model.provider}/${normalized.model.id}`, guidance: request.headers.get("x-minai-guidance") ?? undefined, thinking: JSON.stringify(normalized.thinking ?? "off"), currentTask: "complete" }); const signal = run?.controller.signal ?? request.signal; const result = await this.services.complete(normalized, signal); this.runs?.update(requestId, { usage: result.usage }); this.runs?.remove(requestId); return json(kind === "openai" ? serializeOpenAIChat(result) : kind === "ollama-chat" ? serializeOllamaChat(result) : serializeOllamaGenerate(result));
    } catch (error) { return errorResponse(error); }
  }
  /** Match tool-result messages in a follow-up request to the paused continuation. */
  private toolResultContinuations(normalized: NormalizedChatRequest): Record<string, unknown> | undefined {
    if (!this.services.continuation) return undefined;
    const toolMessages = normalized.messages.filter((message) => message.role === "tool" && message.toolCallId);
    if (toolMessages.length === 0) return undefined;
    const match = this.services.continuation.matchPending(toolMessages.map((message) => message.toolCallId!));
    if (Object.keys(match).length === 0) return undefined;
    const results: Record<string, unknown> = {};
    for (const message of toolMessages) {
      const continuationId = match[message.toolCallId!];
      if (!continuationId || continuationId in results) continue;
      try { results[continuationId] = JSON.parse(message.content) as unknown; } catch { results[continuationId] = message.content; }
    }
    return Object.keys(results).length > 0 ? results : undefined;
  }

  private observeRun(requestId: string, event: unknown): void { const value = event as { type?: string; delta?: string; model?: { provider?: string; id?: string }; result?: { usage?: unknown; model?: { provider?: string; id?: string } } } | undefined; if (!value) return; if (value.model?.provider && value.model.id) this.runs?.update(requestId, { model: `${value.model.provider}/${value.model.id}`, phase: "execution", progress: "model selected; executing" });
 if (value.type === "text_delta" || value.type === "thinking_delta") { const previous = this.runs?.get(requestId)?.state; this.runs?.update(requestId, { output: `${previous?.output ?? ""}${value.delta ?? ""}`, outputMode: value.type === "text_delta" ? "text" : "thinking", phase: value.type === "thinking_delta" ? "planning" : "execution", currentTask: value.type === "thinking_delta" ? "thinking/planning" : "writing answer", progress: value.type === "thinking_delta" ? "model/guidance reasoning" : "streaming answer" }); } if (value.type === "done") this.runs?.update(requestId, { usage: value.result?.usage, currentTask: "complete" }); }
  private cancelResponse(request: Request, runId: string): Response { const owner = request.headers.get("x-minai-owner") ?? undefined; const cancelled = this.runs?.abort(runId, owner) ?? false; return cancelled ? json({ id: runId, status: "cancelling" }) : json({ error: { message: "Run not found or not owned by caller", type: "not_found" } }, 404); }
  private modelsResponse(protocol: "openai" | "ollama"): Response { const models = this.services.listModels?.() ?? []; if (protocol === "openai") return json({ object: "list", data: models.map((model) => ({ id: `${model.provider}/${model.id}`, object: "model", owned_by: model.provider, created: 0 })) }); return json({ models: models.map((model) => ({ name: model.id, model: model.id, modified_at: new Date(0).toISOString(), size: 0, digest: "", details: { provider: model.provider, context_window: model.contextWindow, capabilities: model.capabilities } })) }); }
  private async handleContinuation(request: Request, continuationId: string): Promise<Response> { if (this.runs && !this.runs.ownsContinuation(continuationId, request.headers.get("x-minai-owner") ?? undefined)) throw new HttpProtocolError("Continuation is not owned by caller", "http_invalid_request"); if (!this.services.continuation) return json({ error: { message: "Continuation is unavailable", type: "not_implemented" } }, 501); const bodyText = await readLimitedBody(request, this.options.maxBodyBytes ?? 4_000_000); let body: { results?: Record<string, unknown> }; try { body = JSON.parse(bodyText) as { results?: Record<string, unknown> }; } catch { throw new HttpProtocolError("Continuation body must be valid JSON", "http_invalid_request"); } if (!body.results || typeof body.results !== "object") throw new HttpProtocolError("Continuation results are required", "http_invalid_request"); if (Object.keys(body.results).length > 0 && Object.prototype.hasOwnProperty.call(body.results, continuationId)) { const events = this.services.continuation.resumeBatch(body.results, request.signal); this.runs?.consumeContinuation(continuationId, request.headers.get("x-minai-owner") ?? undefined); return streamResponse(events, (event) => `data: ${JSON.stringify(serializeContinuation(event, "openai"))}\n\n`, "text/event-stream", request.signal); } throw new HttpProtocolError("Continuation path and result IDs do not match", "http_invalid_request"); }
}

function nodeRequestToFetch(request: IncomingMessage, body: ReadableStream<Uint8Array>): Request { const protocol = request.headers["x-forwarded-proto"] === "https" ? "https" : "http"; const host = request.headers.host ?? "localhost"; const headers = new Headers(); for (const [name, value] of Object.entries(request.headers)) if (value !== undefined) headers.set(name, Array.isArray(value) ? value.join(", ") : value); return new Request(`${protocol}://${host}${request.url ?? "/"}`, { method: request.method, headers, body: request.method === "GET" || request.method === "HEAD" ? undefined : body, duplex: "half" } as RequestInit); }
async function writeFetchResponse(response: Response, nodeResponse: ServerResponse): Promise<void> { nodeResponse.statusCode = response.status; response.headers.forEach((value, key) => nodeResponse.setHeader(key, value)); if (!response.body) { nodeResponse.end(); return; } const reader = response.body.getReader(); try { while (true) { const next = await reader.read(); if (next.done) break; if (!nodeResponse.write(Buffer.from(next.value))) await new Promise<void>((resolve) => nodeResponse.once("drain", resolve)); } } finally { reader.releaseLock(); nodeResponse.end(); } }
export async function startMinaiHttpServer(handler: MinaiHttpHandler, options: { host?: string; port: number }): Promise<MinaiHttpServer> { const server = createServer(async (nodeRequest, nodeResponse) => { const abort = new AbortController(); const onClose = () => abort.abort(new Error("HTTP client disconnected")); nodeRequest.on("aborted", onClose); nodeRequest.on("close", onClose); const body = new ReadableStream<Uint8Array>({ start(controller) { nodeRequest.on("data", (chunk: Buffer) => controller.enqueue(new Uint8Array(chunk))); nodeRequest.on("end", () => controller.close()); nodeRequest.on("error", (error) => controller.error(error)); }, cancel() { nodeRequest.destroy(); } }); try { await writeFetchResponse(await handler.handle(nodeRequestToFetch(nodeRequest, body)), nodeResponse); } catch (error) { if (!nodeResponse.headersSent) { nodeResponse.statusCode = 500; nodeResponse.end(JSON.stringify({ error: String(error) })); } else nodeResponse.destroy(); } finally { nodeRequest.off("aborted", onClose); nodeRequest.off("close", onClose); } }); await new Promise<void>((resolve, reject) => { server.once("error", reject); server.listen(options.port, options.host ?? "127.0.0.1", () => { server.off("error", reject); resolve(); }); }); return { server, address: () => server.address(), close: () => new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve())) }; }
