import type { ModelReference, AvailableModel } from "./contracts/common.js";
import type { FileModelHostRegistry } from "./file-host-registry.js";
import { StaticModelCatalog, type ModelCatalogService, type ModelHostHealth, type ModelHostService, type ModelInvocation, type ModelResult, type ModelStreamEvent } from "./model.js";

class Semaphore { private active = 0; private readonly waiters: Array<() => void> = []; constructor(private readonly limit: number) { if (!Number.isInteger(limit) || limit < 1) throw new Error("Host concurrency limit must be positive"); } async acquire(): Promise<() => void> { if (this.active < this.limit) { this.active++; return () => this.release(); } await new Promise<void>((resolve) => this.waiters.push(resolve)); this.active++; return () => this.release(); } private release(): void { this.active--; this.waiters.shift()?.(); } }
class BoundedHost implements ModelHostService { constructor(private readonly inner: ModelHostService, private readonly semaphore: Semaphore) {} ready(reference: ModelReference): Promise<boolean> { return this.inner.ready(reference); } health(): Promise<ModelHostHealth> { const host = this.inner as ModelHostService & { health?: () => Promise<ModelHostHealth> }; return host.health ? host.health() : Promise.resolve({ state: "ready", backend: "python-minai" }); } async invoke(invocation: ModelInvocation, signal?: AbortSignal): Promise<ModelResult> { const release = await this.semaphore.acquire(); try { return await this.inner.invoke(invocation, signal); } finally { release(); } } async *stream(invocation: ModelInvocation, signal?: AbortSignal): AsyncIterable<ModelStreamEvent> { const release = await this.semaphore.acquire(); try { yield* this.inner.stream(invocation, signal); } finally { release(); } } }
export type LocalHostRuntimeOptions = { maxConcurrentPerHost?: number; /** Periodically re-probe host health so credential/availability changes are picked up without a restart. 0 disables. */ healthRefreshMs?: number };
export class LocalHostRuntime {
  private readonly hosts = new Map<string, ModelHostService>(); private readonly healthStates = new Map<string, ModelHostHealth>();
  private healthTimer?: ReturnType<typeof setInterval>;
  constructor(private readonly registry: FileModelHostRegistry, options: LocalHostRuntimeOptions = {}) { const limit = options.maxConcurrentPerHost ?? 1; for (const hostId of registry.listHosts()) this.hosts.set(hostId, new BoundedHost(registry.getHost(hostId), new Semaphore(limit))); this.options = options; }
  async start(): Promise<void> { await this.registry.start(); const interval = this.options.healthRefreshMs ?? 60_000; if (interval > 0) this.healthTimer = setInterval(() => { void this.refreshHealth().catch(() => undefined); }, interval); this.healthTimer?.unref?.(); }
  async stop(): Promise<void> { if (this.healthTimer) { clearInterval(this.healthTimer); this.healthTimer = undefined; } await this.registry.stop(); }
  async refreshHealth(): Promise<ReadonlyMap<string, ModelHostHealth>> { await Promise.all([...this.hosts.entries()].map(async ([id, host]) => { try { this.healthStates.set(id, await (host as BoundedHost).health()); } catch (error) { this.healthStates.set(id, { state: "failed", backend: "python-minai", error: error instanceof Error ? error.message : String(error) }); } })); return this.healthStates; }
  host(reference: ModelReference): ModelHostService { const model = this.registry.getModel(reference); if (!model) throw new Error(`Unknown model ${reference.provider}/${reference.id}`); const host = this.hosts.get(this.registry.getModelHostId(reference)); if (!host) throw new Error(`Unknown host for ${reference.provider}/${reference.id}`); return host; }
  model(reference: ModelReference): AvailableModel | undefined { const model = this.registry.getModel(reference); if (!model) return undefined; const state = this.healthStates.get(this.registry.getModelHostId(reference)); return state && state.state !== "ready" ? { ...model, availability: "offline" } : model; }
  private readonly options: LocalHostRuntimeOptions;
  catalog(): ModelCatalogService { return new StaticModelCatalog(this.registry.listModels().filter((model) => this.model(model)?.availability === "ready")); }
  health(hostId: string): ModelHostHealth | undefined { return this.healthStates.get(hostId); }
}
